name: Check push container

on:
  push:
    branches:
      - push

jobs:
  check-health:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v1

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Check container health
        uses: docker/compose-health-check@v1
        with:
          compose-file: docker-compose.yml
          max-retries: 5
          retry-interval: 10
